# Path: docker-compose.yml

version: '3'

services:
  web:
    build: .
    container_name: magento2
    ports:
      - "8087:80"
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=magento2
      - MYSQL_PORT=3307
