# Path: docker/docker-compose.yml

version: '3'

volumes:
  db-data:
  es-data:

services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: magento2
    ports:
      - "${BASE_URL_PORT:-8087}:80"
    env_file: ../.env
    depends_on:
      - db
      - elasticsearch

  db:
    image: mysql:5.7
    container_name: magento2-db
    ports:
      - "${DB_PORT_EXPOSED:-3317}:${DB_PORT:-3306}"
    env_file: ../.env
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: magento2-elasticsearch
    env_file: ../.env
    environment:
      - discovery.type=single-node
    ports:
      - "${ELASTICSEARCH_PORT_EXPOSED:-9211}:${ELASTICSEARCH_PORT:-9200}"
    volumes:
      - es-data:/usr/share/elasticsearch/data
